version: '3'

tasks:
  build:
    cmds:
      - cmake --preset conan-release
      - cmake --build --preset conan-release

  debug-build:
    cmds:
      - cmake --preset conan-debug
      - cmake --build --preset conan-debug

  build-with-unit-tests:
    cmds:
      - cmake --preset unit-tests
      - cmake --build --preset unit-tests

  build-all:
    cmds:
      - task: build
      - task: debug-build
      - task: build-with-unit-tests

  run:
    dir:
      'build/Release'
    cmds:
      - ./asio_sandbox

  run-unit-tests:
    dir:
      'build/Release'
    cmds:
      - ctest -v