name: Docker Compile Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Prep conan
      run: |
        conan profile detect --force
        conan install . --build=missing -s build_type=Debug
        conan install . --build=missing -s build_type=Release

    - name: Run tasks
      run: |
        task build-all
        task run
        task run-unit-tests